--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Bumyy/Clutch-Core
--- # .
build-by-default: true
branches:
- main
projects: 
  Clutch-Core:
    path: ""
    icon: "/assets/icon.png"
    lint:
      phpstan: false
...

